### ISSUE TITLE
Add more stuff

### ISSUE THREAD

**Issue by ghost** [kamiras/kamira-telnet-botnet#1]

**Comment by kamiras** [comment]
That would be grate ! I do accept all types of changes in my project.

**Comment by ghost** [comment]
> That would be grate ! I do accept all types of changes in my project.

Sure! I have a list of attacks i include in my own projects like XMAS, URG-PSH-SYN, ACK-PSH etc. I'll post them on pastebin so you can add them.

**Comment by ghost** [comment]
but, now that i've actually read the code a little better, i see that it uses hping3. I only have methods which use regular sockets :(
